// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type peertrailEvent struct {
	_      structs.HostLayout
	TsNs   uint64
	Uid    uint32
	Auid   uint32
	Ses    uint32
	Pid    uint32
	Tid    uint32
	Daddr  [16]uint8
	Dport  uint16
	Family uint8
	Proto  uint8
	Hook   uint8
	Comm   [16]int8
	_      [7]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	peertrailMapDrops       = "drops"
	peertrailMapEvents      = "events"
	peertrailProgOnConnect4 = "on_connect4"
	peertrailProgOnConnect6 = "on_connect6"
	peertrailProgOnSendmsg4 = "on_sendmsg4"
	peertrailProgOnSendmsg6 = "on_sendmsg6"
	peertrailVarUnused      = "unused"
)

// loadPeertrail returns the embedded CollectionSpec for peertrail.
func loadPeertrail() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PeertrailBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load peertrail: %w", err)
	}

	return spec, err
}

// loadPeertrailObjects loads peertrail and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*peertrailObjects
//	*peertrailPrograms
//	*peertrailMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPeertrailObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPeertrail()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// peertrailSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type peertrailSpecs struct {
	peertrailProgramSpecs
	peertrailMapSpecs
	peertrailVariableSpecs
}

// peertrailProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type peertrailProgramSpecs struct {
	OnConnect4 *ebpf.ProgramSpec `ebpf:"on_connect4"`
	OnConnect6 *ebpf.ProgramSpec `ebpf:"on_connect6"`
	OnSendmsg4 *ebpf.ProgramSpec `ebpf:"on_sendmsg4"`
	OnSendmsg6 *ebpf.ProgramSpec `ebpf:"on_sendmsg6"`
}

// peertrailMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type peertrailMapSpecs struct {
	Drops  *ebpf.MapSpec `ebpf:"drops"`
	Events *ebpf.MapSpec `ebpf:"events"`
}

// peertrailVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type peertrailVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// peertrailObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPeertrailObjects or ebpf.CollectionSpec.LoadAndAssign.
type peertrailObjects struct {
	peertrailPrograms
	peertrailMaps
	peertrailVariables
}

func (o *peertrailObjects) Close() error {
	return _PeertrailClose(
		&o.peertrailPrograms,
		&o.peertrailMaps,
	)
}

// peertrailMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPeertrailObjects or ebpf.CollectionSpec.LoadAndAssign.
type peertrailMaps struct {
	Drops  *ebpf.Map `ebpf:"drops"`
	Events *ebpf.Map `ebpf:"events"`
}

func (m *peertrailMaps) Close() error {
	return _PeertrailClose(
		m.Drops,
		m.Events,
	)
}

// peertrailVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPeertrailObjects or ebpf.CollectionSpec.LoadAndAssign.
type peertrailVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// peertrailPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPeertrailObjects or ebpf.CollectionSpec.LoadAndAssign.
type peertrailPrograms struct {
	OnConnect4 *ebpf.Program `ebpf:"on_connect4"`
	OnConnect6 *ebpf.Program `ebpf:"on_connect6"`
	OnSendmsg4 *ebpf.Program `ebpf:"on_sendmsg4"`
	OnSendmsg6 *ebpf.Program `ebpf:"on_sendmsg6"`
}

func (p *peertrailPrograms) Close() error {
	return _PeertrailClose(
		p.OnConnect4,
		p.OnConnect6,
		p.OnSendmsg4,
		p.OnSendmsg6,
	)
}

func _PeertrailClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed peertrail_bpfel.o
var _PeertrailBytes []byte
